### ISSUE TITLE
Clustering the dataset

### ISSUE THREAD

**Issue by MayarOssama** [RutgersDM/DKGR#2]
Hello, could you clarify the clustering process of the dataset? I was testing with the graph.txt of nell trying to extract the rest of the files (training and the embeddings and the JSON files) and couldn't get the same results as running on the existing nell folder, I used TransE and ComplEX for the KG embedding and to get the clusters but it didn't work😅.

I m working on an end-to-end framework and wanted to include your approach.

Thanks in advance.

**Comment by yuanzx33033** [comment]
Hey, thanks for your interest in our work.

The detailed steps for data pre-processing are:
1) Use TransE (or other pretrained methods) to generate KG embeddings.
2) Use the "pretraining.py" to obtain the mapping from entity node to cluster node.
3) Move the "entity2clusterid.txt" file into the target dataset folder "dataset/{dataset_name}/", e.g., "dataset/nell/".
4) Run the "code/data/preprocessing_scripts/create_vocab.py"

Hope the above information is helpful to you.

**Comment by MayarOssama** [comment]
Thank you so much, I think my problem was with the embeddings as I was getting the same results 😂
